### PR TITLE
Add dogecoind-rpc and needed methods

### PR DESCRIPTION
**Pull request by jackbonaguro**

### CODE REVIEW

**Review by nickewansmith — APPROVED** [review]
LGTM

- tested getBlock with and without verbose option
- tested getBlockHash

**Review by jguthrie7 — DISMISSED** [review]
Approving as proxy for nick

**Review by nickewansmith — APPROVED** [review]
Looks like tests are now passing in CI, LGTM

**Review by jguthrie7 — APPROVED** [review]
Again Approving as proxy for nick

**Pull request merged**
